# Dracula

spacing         = 3
hide_ascii      = true
key_color       = "#9580FF"
separator_color	= "#FF80BF"
separator		    = "❱"

[box]
title			      = "┤ System Info├"
border          = "Rounded"
visible         = true

[palette]
glyph           = " ██ "
type			      = "Light"
visible         = true


[bar]
glyph           = "●"
hide_delimiters = true
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "#FF7001"
