---
# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  padding:
    x: 5
    y: 0

  # Window decorations
  decorations: buttonless

  # Startup Mode (changes require restart)
  # startup_mode: Windowed
  startup_mode: Fullscreen

  # Window title
  title: Alacritty
  dynamic_title: true

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

scrolling:
  history: 5000

# Font configuration
font:
  normal:
    family: Hack Nerd Font Mono

  bold:
    family: Hack Nerd Font Mono

  italic:
    family: Hack Nerd Font Mono

  bold_italic:
    family: Hack Nerd Font Mono

  # Point size
  size: 15.0

  # Offset
  offset:
    x: 1
    y: 1

# Colors (Srcery)
colors:
  # Default colors
  primary:
    background: '#1c1b19'
    foreground: '#fce8c3'

  # Cursor colors
  cursor:
    text: CellBackground
    cursor: '#fbb829'

  # Normal colors
  normal:
    black:   '#1c1b19'
    red:     '#ef2f27'
    green:   '#519f50'
    yellow:  '#fbb829'
    blue:    '#2c78bf'
    magenta: '#e02c6d'
    cyan:    '#0aaeb3'
    white:   '#d0bfa1'

  # Bright colors
  bright:
    black:   '#918175'
    red:     '#f75341'
    green:   '#98bc37'
    yellow:  '#fed06e'
    blue:    '#68a8e4'
    magenta: '#ff5c8f'
    cyan:    '#53fde9'
    white:   '#fce8c3'

# Background opacity
background_opacity: 0.95

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
window.dynamic_title: true

# Cursor style
cursor:
  style: Block

# Live config reload (changes require restart)
live_config_reload: true

# Mouse
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  url:
    launcher:
      program: open
      args: []

# Mouse bindings
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

# Key bindings
key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }

    # OSX
  - { key: 28,      mods: Alt, chars: "{" }
  - { key: 25,      mods: Alt, chars: "}" }
  - { key: 37,      mods: Alt, chars: "@" }
  - { key: 26,      mods: Alt|Shift, chars: "\\" }
  - { key: 26,      mods: Alt, chars: "|" }
  - { key: 45,      mods: Alt, chars: "~" }
  - { key: 23,      mods: Alt, chars: "[" }
  - { key: 22,      mods: Alt, chars: "]" }
  - { key: Return,   mods: Command,       action: ToggleFullscreen }

  # arrow keys
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
