#!/bin/bash
set -e

# Determine the general system type
system_type=$(uname -s)

################################################################################
# General tasks
################################################################################

# Create a temporary directory
mkdir -p "${HOME}/tmp"

if [ "$system_type" = "Linux" ]; then
  . "${HOME}/.config/yadm/bootstrap_linux"
fi

if [ "$system_type" = "Darwin" ]; then
  . "${HOME}/.config/yadm/bootstrap_osx"
fi

echo finished > /tmp/yadm-bootstrap
