#cloud-config
disable_root: true
users:
  - name: steinbrueckri
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id: gh:steinbrueckri
    shell: /bin/fish
package_update: true
package_upgrade: true
packages:
  - vim
  - neovim
  - fish
  - docker
  - avahi-daemon
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers steinbrueckri' /etc/ssh/sshd_config
  - sudo curl -fsSL https://get.docker.com | sudo bash
  - sudo systemctl enable docker
  - sudo systemctl enable -s HUP ssh
  - sudo groupadd docker
  - sudo usermod -aG docker steinbrueckri
