# git:
#   paging:
#     colorArg: always
#     useConfig: false
#     pager: delta --dark --color-only --side-by-side
#   skipHookPrefix: WIP
#   autoFetch: true
#   autoRefresh: true
#   branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
#   allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium"
#   overrideGpg: false
#   disableForcePushing: true
#   log:
#     showGraph: "always"
#     showWholeGraph: true
#
# os:
#   edit: "nvim"
#   editAtLine: "{{editor}} +{{line}} {{filename}}"
#   open: "tmux new-window '{{command}}'"
#
# refresher:
#   refreshInterval: 10
#   fetchInterval: 60

keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<esc>"
    optionMenu-alt1: "h"
    togglePanel: "<tab>"
  status:
    checkForUpdate: "u"
    recentRepos: "<enter>"
  commits:
    squashDown: "s"
    renameCommit: "r"
