format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:iris) \
"""

palette = "rose-pine-dawn"
command_timeout = 3600

[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[✘\($count\)](bg:overlay fg:love)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[status]
disabled = false
format = "[](fg:overlay)[ ❌ $status ]($style)[](fg:overlay) "
style = "bg:overlay fg:love"
success_symbol = ""
map_symbol = true
recognize_signal_code = true

[time]
disabled = true
format = " [](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%H:%M"
use_12hr = false

[username]
disabled = false
show_always = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)"
style_root = "bg:overlay fg:love"
style_user = "bg:overlay fg:iris"

[hostname]
ssh_only = true
format = "[@$hostname ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
trim_at = "."
disabled = false

# Languages

[c]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elixir]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[scala]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:pine"
format = ' [](fg:overlay)[ ${symbol}${version}(\($virtualenv\) )]($style)[](fg:overlay)'
disabled = false
symbol = " "

[conda]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$environment ]($style)[](fg:overlay)"
disabled = false
symbol = "🅒 "
