kitty:
  type: colorscheme
  path: "~/.config/kitty/kitty.conf"
  regex: "include ./rose-pine-.*"
  replace: "include ./rose-pine-{}.conf"
  cmd: "pkill -SIGUSR1 kitty"

fish:
  type: colorscheme
  path: "~/.config/fish/config.fish"
  regex: "set THEME rose-pine-.*"
  replace: "set THEME rose-pine-{}"

nvim:
  type: colorscheme
  path: "~/.config/nvim/init.lua"
  regex: 'local flavor = ".*"'
  replace: 'local flavor = "{}"'

tmux:
  type: colorscheme
  path: "~/.tmux.conf"
  regex: "set -g @rose_pine_variant '.*'"
  replace: "set -g @rose_pine_variant '{}'"
  cmd: "tmux source-file ~/.tmux.conf"

starship:
  type: colorscheme
  path: "~/.config/starship.toml"
  regex: 'palette = "rose-pine-.*'
  replace: 'palette = "rose-pine-{}"'

bat:
  type: colorscheme
  path: "~/.config/bat/config"
  regex: "--theme=.*"
  replace: '--theme="rose-pine-{}"'

aerc:
  type: colorscheme
  path: "~/.config/aerc/aerc.conf"
  regex: "styleset-name = rose-pine-.*"
  replace: "styleset-name = rose-pine-{}"

eilmeldung:
  type: colorscheme
  path: "~/.config/eilmeldung/.theme"
  regex: "rose-pine-.*"
  replace: "rose-pine-{}"
  cmd: "cat ~/.config/eilmeldung/base.toml ~/.config/eilmeldung/themes/rose-pine-{}.toml > ~/.config/eilmeldung/config.toml"
