name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    # Every day at 06:00
    - cron: "0 6 * * *"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Lint
        run: just lint-md

      - name: Create test results directory
        run: mkdir -p .test_results && chmod 777 .test_results

      - name: Run tests
        run: just test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: .test_results/
          if-no-files-found: ignore

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: .test_results/*.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results
