name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    # Every day at 06:00
    - cron: "0 6 * * *"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Run tests
        run: just lint-md && just test

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: .test_results/*.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results
